server:
  port: 9003

eureka:
  datacenter: moscow
  instance:
    hostname: localhost
    metadataMap:
      instanceId: EUREKA01_${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

ribbon:
  ConnectTimeout: 100000
  ReadTimeout: 300000

  
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

app: 
  home: 'omsk'
  work: 'new-york'